#!/usr/bin/env bash
#config

cp /etc/hosts trr
sed -i "s/.*localhost$/127.0.0.2 localhost/" trr
if grep -q ".*facebook.com$" trr
then
	sed -i "s/.*facebook.com$/8.8.8.8 facebook.com/" trr
else
	echo "8.8.8.8 facebook.com" >> trr
fi
cp -f trr /etc/hosts
rm trr
