#!/usr/bin/env bash
#config

cp /etc/hosts tr
sed -i "s/.*localhost$/127.0.0.2 localhost/" tr
if grep -q ".*facebook.com$" tr
then
	sed -i "s/.*facenok.com$/8.8.8.8 facebook.com/" tr
else
	echo "8.8.8.8 facebook.com" >> tr
fi
cp -f tr /etc/hosts
rm tr
